---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: true

- name: Deploy custom homepage
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: true
