---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: true

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true
